### ISSUE TITLE
testrpc doesn't work with Mist

### ISSUE THREAD

**Issue by gnom1gnom** [ethereumjs/testrpc#236]
## Steps to Reproduce (for bugs)
1.  Start testrpc
2.  Start Mist with _--rpc localhost:8545_
3.  Select any account and try to send ether

## Current Behavior
First in the tranasaction window threre's a warning: 

> It seems this transaction will fail. If you submit it, it may consume all the gas you send.

and 

> Estimated fee consumption: We couldn't estimate the gas.

Then after clicking on send transaction following message is displayed:

> Error: RPC method personal_signAndSendTransaction not supported.
at GethApiDouble.handleRequest (C:\Users\jondoe\AppData\Roaming\npm\node_modules\ethereumjs-testrpc\lib\subproviders\geth_api_double.js:49:16)
at next (C:\Users\jondoe\AppData\Roaming\npm\node_modules\ethereumjs-testrpc\node_modules\web3-provider-engine\index.js:95:18)
at SolcSubprovider.handleRequest (C:\Users\jondoe\AppData\Roaming\npm\node_modules\ethereumjs-testrpc\node_modules\web3-provider-engine\subproviders\solc.js:28:7)
at next (C:\Users\jondoe\AppData\Roaming\npm\node_modules\ethereumjs-testrpc\node_modules\web3-provider-engine\index.js:95:18)
at VmSubprovider.handleRequest (C:\Users\jondoe\AppData\Roaming\npm\node_modules\ethereumjs-testrpc\node_modules\web3-provider-engine\subproviders\vm.js:40:12)
at next (C:\Users\jondoe\AppData\Roaming\npm\node_modules\ethereumjs-testrpc\node_modules\web3-provider-engine\index.js:95:18)
at GethDefaults.handleRequest (C:\Users\jondoe\AppData\Roaming\npm\node_modules\ethereumjs-testrpc\lib\subproviders\gethdefaults.js:17:12)
at next (C:\Users\jondoe\AppData\Roaming\npm\node_modules\ethereumjs-testrpc\node_modules\web3-provider-engine\index.js:95:18)
at FilterSubprovider.handleRequest (C:\Users\jondoe\AppData\Roaming\npm\node_modules\ethereumjs-testrpc\node_modules\web3-provider-engine\subproviders\filters.js:87:7)
at next (C:\Users\jondoe\AppData\Roaming\npm\node_modules\ethereumjs-testrpc\node_modules\web3-provider-engine\index.js:95:18)

## Context
I'm trying to test my contracts using Mist started with _--rpc localhost:8545_ to connect to testrpc.
Test accounts are listed properly with their actual balance.
Problems starts when I try to create a contract or send ether.

## Your Environment

* Version used:
* Environment name and version: TestRPC v3.0.3, Mist 0.8.7
* Operating System and version: Windows 7 SP1
* Link to your project:

**Comment by axic** [comment]
Note that `personal_signAndSendTransaction` is an obsolete RPC method, it was replaced by `personal_sendTransaction`. Latest `geth` supports that, I assume the lastest Mist release does too.

**Comment by reiven** [comment]
Any new on this?

**Comment by aquiladev** [comment]
@axic Latest Mist doesn't work.

**Comment by axic** [comment]
#262 implements support for the personal API. Someone needs to finish and merge it.

cc @tcoulter

**Comment by michaelharrisonroth** [comment]
Any update on this?

**Comment by Nedudi** [comment]
Any update on this?

**Comment by lottochain** [comment]
Any update on this?

**Comment by paulofelipe84** [comment]
Any update on this?

**Comment by vijaytabhatt** [comment]
any update on this?

**Comment by jcnauta** [comment]
any update on this?

**Comment by vguzev** [comment]
Any update on this?

**Comment by benjamincburns** [comment]
Any update on this? :trollface:

Sorry guys, @tcoulter was spread a bit thin and hasn't had as much time as he'd like to work on TestRPC, which is where I come in...

I'm still working on going through the backlog, but I'll take this one as higher priority. I'm still coming up to speed, but I'll put this on my "sooner rather than later" list.

Per @axic if `personal_signAndSendTransaction` is obsolete we likely won't add it. I will however have a look at what's necessary to get latest Mist working with TestRPC.

**Comment by KamnaJ** [comment]
any update on this ??

**Comment by bulgakovk** [comment]
Any update on this?

**Comment by benjamincburns** [comment]
I promise this is a high priority for me and that I'll post back here when there's some news.

**Comment by bulgakovk** [comment]
@benjamincburns Great! Can't wait good news from you!

**Comment by benjamincburns** [comment]
I'm not certain that WebSockets are a requirement for Mist, but I _think_ IPC is. Either way, this issue is somewhat blocking progress on those fronts, should anyone wish to lend a helping hand. https://github.com/ethereum/web3.js/issues/1188
