### ISSUE TITLE
'from' is required for estimateGas call

### ISSUE THREAD

**Issue by area** [ethereumjs/testrpc#25]
Unlike `geth`, the 'from' field is required when making an `estimateGas` call. Without it, the following is returned:

```
"AssertionError: false == true
    at Object.exports.pubToAddress.exports.publicToAddress (/Users/alex/Projects/Colony/testrpc/node_modules/ethereumjs-util/index.js:301:3)
    at FakeTransaction.Transaction.getSenderAddress (/Users/alex/Projects/Colony/testrpc/node_modules/ethereumjs-tx/index.js:147:24)
    at populateCache (/Users/alex/Projects/Colony/testrpc/node_modules/ethereumjs-vm/lib/runTx.js:73:20)
    at /Users/alex/Projects/Colony/testrpc/node_modules/async/lib/async.js:718:13
    at iterate (/Users/alex/Projects/Colony/testrpc/node_modules/async/lib/async.js:262:13)
    at async.forEachOfSeries.async.eachOfSeries (/Users/alex/Projects/Colony/testrpc/node_modules/async/lib/async.js:281:9)
    at _parallel (/Users/alex/Projects/Colony/testrpc/node_modules/async/lib/async.js:717:9)
    at Object.async.series (/Users/alex/Projects/Colony/testrpc/node_modules/async/lib/async.js:739:9)
    at VM.module.exports [as runTx] (/Users/alex/Projects/Colony/testrpc/node_modules/ethereumjs-vm/lib/runTx.js:40:9)
    at VmSubprovider.runVm (/Users/alex/Projects/Colony/testrpc/node_modules/web3-provider-engine/subproviders/vm.js:111:6)
```

The workaround for `eth_call` can be seen at https://github.com/ethereumjs/testrpc/blob/master/lib/blockchain.js#L325-L326 , but as `estimateGas` is dealt with by `web3-provider-engine`, I don't think a similar fix can be applied here.

**Comment by tcoulter** [comment]
Fixed, w/ test. ethereumjs-testrpc v1.2.1 pushed to npm.
